return {
    "nvim-treesitter/nvim-treesitter",
    event = { "BufReadPost", "BufNewFile" },
    dependencies = {
        "nvim-treesitter/nvim-treesitter-textobjects",
    },
    main = "nvim-treesitter.configs",
    build = ":TSUpdate",
    opts = {
        auto_install = true,
        ensure_installed = {
            "rust",
            "lua",
            "toml",
            "json",
            "yaml",
            "bash",
            "dockerfile",
            "markdown",
            "markdown_inline",
            "javascript",
            "typescript",
            "html",
            "css",
            "regex",
            "vim",
            "vimdoc",
            "query",
            "diff",
            "gitattributes",
            "gitignore",
            "gitcommit",
            "git_rebase",
            "solidity",
            "circom",
        },
        highlight = { enable = true },
        indent = { enable = true },
        textobjects = {
            select = {
                enable = true,
                lookahead = true,
                keymaps = {
                    ["af"] = "@function.outer",
                    ["if"] = "@function.inner",
                    ["ac"] = "@class.outer",
                    ["ic"] = { query = "@class.inner", desc = "Select inner part of a class region" },
                    ["as"] = { query = "@scope", query_group = "locals", desc = "Select language scope" },
                },
                selection_modes = {
                    ["@parameter.outer"] = "v",
                    ["@function.outer"] = "V",
                    ["@class.outer"] = "<c-v>",
                },
                include_surrounding_whitespace = false,
            },
        },
    },
}
